version: 2
jobs:
  build:
    working_directory: ~/autocomplete
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          command: |
            sudo apt install graphviz
            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - save_cache:
          key: deps1-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            pip install -e .
            pytest tests/
